name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
      - run: yarn run lint
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
      - run: yarn run type-check
  test:
    needs:
      - linting
      - type-check
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
      - run: yarn test
  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
      - run: yarn run build
